import './style.css'

document.querySelector('#app').innerHTML = `
<header class="site-header"><a class="wordmark" href="#top"><span>blvck</span>motion<span>.</span></a><button class="menu-toggle" type="button" aria-expanded="false">Menu +</button><nav class="site-nav"><a href="#services">Services</a><a href="#systems">Systems</a><a href="#about">About</a><a class="nav-cta" href="#contact">Start a project ↗</a></nav></header>
<main id="top">
<section class="hero section-wrap"><div class="hero-copy"><p class="eyebrow">Content production studio / Kaduna, NG</p><h1>Your entire<br><em>content team.</em><br>Under one roof.</h1><p class="hero-intro">We make the content that keeps ambitious brands moving, from first frame to final post</p><a class="button button-light" href="#contact">Start a project ↗</a></div><div class="hero-visual"><div class="hero-image"></div><span class="image-label">01 / The work is the proof</span><span class="hero-stamp">BMS<br><b>24</b></span></div><div class="hero-meta mono"><span>EST. 2024</span><span>EDIT / SHOOT / DESIGN / MOTION</span><span>SCROLL TO EXPLORE ↓</span></div></section>
<section class="ticker">VIDEO EDITING <i>✳</i> VIDEOGRAPHY <i>✳</i> GRAPHIC DESIGN <i>✳</i> MOTION GRAPHICS <i>✳</i> VIDEO EDITING</section>
<section id="services" class="services section-wrap section-space"><div class="section-heading"><p class="eyebrow">What we do</p><h2>One creative<br><em>language.</em></h2></div><div class="service-grid"><article class="service"><span class="service-number mono">01</span><h3>Video<br>editing</h3><p>Short-form that stops the scroll. Long-form that holds attention.</p><a href="/portfolio/video-editing/" target="_blank" rel="noreferrer">↗</a></article><article class="service"><span class="service-number mono">02</span><h3>Video-<br>graphy</h3><p>On-location capture built around your brand, people, and place.</p><a href="/portfolio/videography/" target="_blank" rel="noreferrer">↗</a></article><article class="service"><span class="service-number mono">03</span><h3>Graphic<br>design</h3><p>Visual systems that make every detail feel unmistakably yours.</p><a href="/portfolio/graphic-design/" target="_blank" rel="noreferrer">↗</a></article><article class="service"><span class="service-number mono">04</span><h3>Motion<br>graphics</h3><p>Bringing life to your brand's message in fun ways.</p><a href="/portfolio/motion-graphics/" target="_blank" rel="noreferrer">↗</a></article></div></section>
<section id="systems" class="systems section-space"><div class="section-wrap systems-inner"><div class="section-heading"><p class="eyebrow">Monthly content systems</p><h2>Consistency is<br><em>a strategy.</em></h2></div><div><p class="large-copy">Stop piecing your content together. Choose a rhythm, get a dedicated creative partner, and give your audience something to always come back to.</p><div class="package-tabs"><button class="active" data-package="Lite">Lite</button><button data-package="Standard">Standard</button><button data-package="Pro">Pro</button></div><div class="package-detail"><div><span class="mono package-label">MONTHLY PACKAGE / <b id="package-name">LITE</b></span><h3 id="package-title">A sharp start.</h3><p id="package-copy">For businesses ready to show up with intention. A focused monthly flow of edits and design assets.</p></div><ul id="package-list"><li>4 short-form edits</li><li>8 graphic design</li><li>1 design package</li></ul></div></div></div></section>
<section id="about" class="about section-wrap section-space"><div class="about-mark">B<span>/</span>M</div><div><p class="eyebrow">The studio</p><h2>Built for brands<br>that are <em>going places.</em></h2><p class="about-copy">blvckmotionstudio is your full content department, without the overhead. Founded by DevHameed in Kaduna, we bring four creative disciplines into one clear workflow and one point of contact.</p></div></section>
<section id="contact" class="contact section-wrap"><p class="eyebrow">Have a brief in mind?</p><h2>Let's make<br>something <em>move.</em></h2><a class="button button-outline" href="#project-modal">Start a project ↗</a></section></main>
<div class="modal" id="project-modal" aria-hidden="true"><div class="modal-backdrop"></div><section class="modal-panel" role="dialog" aria-modal="true"><button class="modal-close" type="button">×</button><p class="eyebrow">Start a project</p><h2>Tell us what<br><em>you have in mind.</em></h2><form id="project-form"><label>Name or brand<input name="name" autocomplete="name" required></label><label>Email<input name="email" type="email" autocomplete="email" required></label><label>What would you love to work on?<textarea name="project" rows="4" required></textarea></label><button class="button button-light" type="submit">Send enquiry ↗</button><p class="form-status" role="status"></p></form></section></div>`

const packages = { Lite: ['A sharp start.', 'For businesses ready to show up with intention. A focused monthly flow of edits and design assets.', ['4 short-form edits', '8 graphic design', '1 design package']], Standard: ['Your content engine.', 'A dependable creative rhythm for brands ready to publish consistently and grow their presence.', ['8 short-form edits', '2 long-form edits', '10 graphic design', '1 design package']], Pro: ['Full creative department.', 'The complete system for teams who want content handled end-to-end, every month.', ['8 short-form edits', '4 long-form edits', '1 brand-film', '15 graphic design', 'Motion-graphics embedded', '1 design package']] }
document.querySelectorAll('.package-tabs button').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('.package-tabs button').forEach((tab) => tab.classList.remove('active')); button.classList.add('active'); const selected = packages[button.dataset.package]; document.querySelector('#package-name').textContent = button.dataset.package.toUpperCase(); document.querySelector('#package-title').textContent = selected[0]; document.querySelector('#package-copy').textContent = selected[1]; document.querySelector('#package-list').innerHTML = selected[2].map((item) => `<li>${item}</li>`).join('') }))
document.querySelector('.menu-toggle').addEventListener('click', (event) => { const open = event.currentTarget.getAttribute('aria-expanded') === 'true'; event.currentTarget.setAttribute('aria-expanded', String(!open)); document.querySelector('.site-nav').classList.toggle('open', !open) })
const modal = document.querySelector('#project-modal'); const closeModal = () => { modal.classList.remove('open'); modal.setAttribute('aria-hidden', 'true'); document.body.classList.remove('modal-open') }; document.querySelectorAll('a[href="#contact"], a[href="#project-modal"]').forEach((link) => link.addEventListener('click', (event) => { event.preventDefault(); modal.classList.add('open'); modal.setAttribute('aria-hidden', 'false'); document.body.classList.add('modal-open') })); modal.querySelector('.modal-backdrop').addEventListener('click', closeModal); modal.querySelector('.modal-close').addEventListener('click', closeModal)
document.querySelector('#project-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = event.currentTarget; const status = form.querySelector('.form-status'); status.textContent = 'Sending...'; try { const response = await fetch('/api/contact', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(form))) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error || 'Request failed'); form.reset(); status.textContent = 'Thanks. Your enquiry is on its way.' } catch (error) { status.textContent = error.message || 'Something went wrong.' } })
